spring:
    config:
        import: "classpath:rabbitmq.yml"
    application:
        name: mslastfm

    data:
        mongodb:
            uri: mongodb://${MONGODB_HOST}:27017/mslastfm
            database: mslastfm
            port: 27017
            host: ${MONGODB_HOST}
            username: ${MONGODB_USERNAME}
            password: ${MONGODB_PASSWORD}
    

lastfm:
    api:
        key: ${LASTFM_API_KEY}

aws:
    s3:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
        bucketName: ${AWS_BUCKET_NAME}
        region: ${AWS_REGION}

rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}