spring:
    config:
        import: classpath:/config.yml
    application:
        name: msspotify
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

server:
  port: 8082
