spring:
    application:
      name: msrecommendation
    config:
      import: "classpath:rabbitmq.yml"
    ai:
      anthropic:
        api-key: ${ANTHROPIC_API_KEY}
        chat:
          options:
            model: claude-3-5-sonnet-20240620
            temperature: 0.7
            max-tokens: 450

rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


server:
  port: 8083

