name: Continuous Integration msspotify

on:
    push:
      paths:
        - 'msspotify/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: Build project
              run: |
                cd msspotify
                mvn clean install

            - name: Build Docker image
              run: | 
                cd msspotify
                docker build -t ${{secrets.DOCKER_USERNAME}}/msspotify .

            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Push Docker image
              run: docker push ${{secrets.DOCKER_USERNAME}}/msspotify